name: Progress
favicon: null
layout_spectrum: 0.9103735398966819
typography_spectrum: 0.35896529885940254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5849617735948414
  lightness: 0.0913051669485867
  saturation: 0.36621971311978996
  rhythmicContrast: 0.7979127869475633
purpose: []
